#!/usr/bin/python
#
#

import os

print """

Module:

 _   _ _ __ (_)      _ __   __ _ ___ ___
| | | | '_ \| |_____| '_ \ / _` / __/ __|
| |_| | | | | |_____| |_) | (_| \__ \__ \
 \__,_|_| |_|_|     | .__/ \__,_|___/___/
                    |_|

\nWhat is 'Uni-Pass'?
Uni_Pass is a module
that generates a wordlist of possible
passwords based on the input you've
entered at each prompt.
About 75%-80% of the time people don't
choose difficult passwords, they would
typically use something with their 'Name,
DOB(date of birth), and a couple symbols.
Any Hacker can easily guess
their password though a tool like this.
With this script, you'll be able to
generate a wordlist of the
\n'MOST-COMMON-PASSWORD-FORMAT'

Here's a example, for someone by the name of
'Jack James' who is born on '03-15-1982'

Jack might of used the Following:

\tjack james 1982
\tjack.james.1982
\tjackjames03151952
\tjackjames-1982

And 'Uni-Pass' does just that!!!

"""

################################################
##       Prompts you for basic info to        ##
################################################

first_name = raw_input("First Name: ")
last_name = raw_input("\nLast Name: ")
#nick_name = raw_input("Nick Name: ")
middle_name = raw_input("\nMiddle Name: ")
middle_init = raw_input("\nMiddle Initial: ")
mob = raw_input("\nMonth of Birth: ")
dob = raw_input("\nDay of Birth: ")
yob = raw_input("\nYear of Birth: ")
#last_4 = raw_input("Last 4 Digits of Cell-Phone Number: ")
#pet = raw_input("Pet's Name: ")

print """
##############################################################
[!]...Generating, list of possible passwords, please wait..."
##############################################################
"""

################################################
##Scrambling of users input and saving to file##
################################################

#import Output
file = "uni-wordlist.txt"
wordlist = open(file, 'w')

wordlist.write(first_name + " " + last_name)
wordlist.write("\n")
wordlist.write(first_name + "_" + last_name)
wordlist.write("\n")
wordlist.write(first_name + "-" + last_name)
wordlist.write("\n")
wordlist.write(first_name + "." + last_name)
wordlist.write("\n")
wordlist.write(first_name + last_name)
wordlist.write("\n")
wordlist.write(first_name + " " + last_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + last_name + "_" + mob + "_" + dob + "_" + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + last_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + last_name + "-" + mob + "-" + dob + "-" + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + last_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + last_name + "." + mob + "." + dob + "." + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + last_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(first_name + last_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(first_name + " " + last_name + mob + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + last_name + mob + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + last_name + mob + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + last_name + mob + yob)
wordlist.write("\n")
wordlist.write(first_name + " " + last_name + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + last_name + "_" + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + last_name + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + last_name + "-" + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + last_name + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + last_name + "." + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + last_name + yob)
wordlist.write("\n")
wordlist.write(first_name + last_name + yob)
wordlist.write("\n")
wordlist.write(first_name + " " + middle_init + last_name)
wordlist.write("\n")
wordlist.write(first_name + "_" + middle_init + last_name)
wordlist.write("\n")
wordlist.write(first_name + "-" + middle_init + last_name)
wordlist.write("\n")
wordlist.write(first_name + "." + middle_init + last_name)
wordlist.write("\n")
wordlist.write(first_name + middle_init + last_name)
wordlist.write("\n")
wordlist.write(first_name + " " + middle_init + last_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + middle_init + last_name + "_" + mob + "_" + dob + "_" + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + middle_init + last_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + middle_init + last_name + "-" + mob + "-" + dob + "-" + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + middle_init + last_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + middle_init + last_name + "." + mob + "." + dob + "." + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + middle_init + last_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(first_name + middle_init + last_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(first_name + " " + middle_init + last_name + mob + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + middle_init + last_name + mob + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + middle_init + last_name + mob + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + middle_init + last_name + mob + yob)
wordlist.write("\n")
wordlist.write(first_name + " " + middle_init + last_name + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + middle_init + last_name + "_" + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + middle_init + last_name + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + middle_init + last_name + "-" + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + middle_init + last_name + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + middle_init + last_name + "." + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + middle_init + last_name + yob)
wordlist.write("\n")
wordlist.write(first_name + middle_init + last_name + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + middle_init + mob + "_" + dob + "_" + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + middle_init + mob + "-" + dob + "-" + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + middle_init + mob + "." + dob + "." + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + middle_init + mob + "_" + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + middle_init + mob + "-" + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + middle_init + mob + "." + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + middle_init + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + middle_init + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + middle_init + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + mob + "_" + dob + "_" + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + mob + "-" + dob + "-" + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + mob + "." + dob + "." + yob)
wordlist.write("\n")
wordlist.write(first_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + mob + "_" + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + mob + "-" + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + mob + "." + yob)
wordlist.write("\n")
wordlist.write(first_name + mob + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + yob)
wordlist.write("\n")
wordlist.write(first_name + yob)
wordlist.write("\n")
wordlist.write(last_name + " " + first_name)
wordlist.write("\n")
wordlist.write(last_name + "_" + first_name)
wordlist.write("\n")
wordlist.write(last_name + "-" + first_name)
wordlist.write("\n")
wordlist.write(last_name + "." + first_name)
wordlist.write("\n")
wordlist.write(last_name + first_name)
wordlist.write("\n")
wordlist.write(last_name + " " + first_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + first_name + "_" + mob + "_" + dob + "_" + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + first_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + first_name + "-" + mob + "-" + dob + "-" + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + first_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + first_name + "." + mob + "." + dob + "." + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + first_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(last_name + first_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(last_name + " " + first_name + mob + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + first_name + mob + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + first_name + mob + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + first_name + mob + yob)
wordlist.write("\n")
wordlist.write(last_name + " " + first_name + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + first_name + "_" + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + first_name + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + first_name + "-" + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + first_name + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + first_name + "." + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + first_name + yob)
wordlist.write("\n")
wordlist.write(last_name + first_name + yob)
wordlist.write("\n")
wordlist.write(last_name + " " + middle_init + first_name)
wordlist.write("\n")
wordlist.write(last_name + "_" + middle_init + first_name)
wordlist.write("\n")
wordlist.write(last_name + "-" + middle_init + first_name)
wordlist.write("\n")
wordlist.write(last_name + "." + middle_init + first_name)
wordlist.write("\n")
wordlist.write(last_name + middle_init + first_name)
wordlist.write("\n")
wordlist.write(last_name + " " + middle_init + first_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + middle_init + first_name + "_" + mob + "_" + dob + "_" + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + middle_init + first_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + middle_init + first_name + "-" + mob + "-" + dob + "-" + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + middle_init + first_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + middle_init + first_name + "." + mob + "." + dob + "." + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + middle_init + first_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(last_name + middle_init + first_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(last_name + " " + middle_init + first_name + mob + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + middle_init + first_name + mob + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + middle_init + first_name + mob + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + middle_init + first_name + mob + yob)
wordlist.write("\n")
wordlist.write(last_name + " " + middle_init + first_name + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + middle_init + first_name + "_" + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + middle_init + first_name + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + middle_init + first_name + "-" + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + middle_init + first_name + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + middle_init + first_name + "." + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + middle_init + first_name + yob)
wordlist.write("\n")
wordlist.write(last_name + middle_init + first_name + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + middle_init + mob + "_" + dob + "_" + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + middle_init + mob + "-" + dob + "-" + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + middle_init + mob + "." + dob + "." + yob)
wordlist.write("\n")
wordlist.write(last_name + middle_init + mob + dob + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + middle_init + mob + "_" + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + middle_init + mob + "-" + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + middle_init + mob + "." + yob)
wordlist.write("\n")
wordlist.write(last_name + middle_init + mob + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + middle_init + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + middle_init + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + middle_init + yob)
wordlist.write("\n")
wordlist.write(last_name + middle_init + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + mob + "_" + dob + "_" + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + mob + "-" + dob + "-" + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + mob + "." + dob + "." + yob)
wordlist.write("\n")
wordlist.write(last_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + mob + "_" + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + mob + "-" + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + mob + "." + yob)
wordlist.write("\n")
wordlist.write(last_name + mob + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + yob)
wordlist.write("\n")
wordlist.write(last_name + yob)
wordlist.write("\n")
wordlist.write(mob + dob + yob)
wordlist.write("\n")
wordlist.write(mob + " " + dob + " " + yob)
wordlist.write("\n")
wordlist.write(mob + "." + dob + "." + yob)
wordlist.write("\n")
wordlist.write(mob + "_" + dob + "_" + yob)
wordlist.write("\n")
wordlist.write(mob + "-" + dob + "-" + yob)
wordlist.write("\n")
wordlist.write(first_name + " " + middle_name + last_name)
wordlist.write("\n")
wordlist.write(first_name + "_" + middle_name + last_name)
wordlist.write("\n")
wordlist.write(first_name + "-" + middle_name + last_name)
wordlist.write("\n")
wordlist.write(first_name + "." + middle_name + last_name)
wordlist.write("\n")
wordlist.write(first_name + middle_name + last_name)
wordlist.write("\n")
wordlist.write(first_name + " " + middle_name + last_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + middle_name + last_name + "_" + mob + "_" + dob + "_" + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + middle_name + last_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + middle_name + last_name + "-" + mob + "-" + dob + "-" + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + middle_name + last_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + middle_name + last_name + "." + mob + "." + dob + "." + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + middle_name + last_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(first_name + middle_name + last_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(first_name + " " + middle_name + last_name + mob + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + middle_name + last_name + mob + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + middle_name + last_name + mob + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + middle_name + last_name + mob + yob)
wordlist.write("\n")
wordlist.write(first_name + " " + middle_name + last_name + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + middle_name + last_name + "_" + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + middle_name + last_name + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + middle_name + last_name + "-" + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + middle_name + last_name + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + middle_name + last_name + "." + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + middle_name + last_name + yob)
wordlist.write("\n")
wordlist.write(first_name + middle_name + last_name + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + middle_name + mob + "_" + dob + "_" + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + middle_name + mob + "-" + dob + "-" + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + middle_name + mob + "." + dob + "." + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + middle_name + mob + "_" + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + middle_name + mob + "-" + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + middle_name + mob + "." + yob)
wordlist.write("\n")
wordlist.write(first_name + "_" + middle_name + yob)
wordlist.write("\n")
wordlist.write(first_name + "-" + middle_name + yob)
wordlist.write("\n")
wordlist.write(first_name + "." + middle_name + yob)
wordlist.write("\n")
wordlist.write(last_name + " " + middle_name + first_name)
wordlist.write("\n")
wordlist.write(last_name + "_" + middle_name + first_name)
wordlist.write("\n")
wordlist.write(last_name + "-" + middle_name + first_name)
wordlist.write("\n")
wordlist.write(last_name + "." + middle_name + first_name)
wordlist.write("\n")
wordlist.write(last_name + middle_name + first_name)
wordlist.write("\n")
wordlist.write(last_name + " " + middle_name + first_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + middle_name + first_name + "_" + mob + "_" + dob + "_" + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + middle_name + first_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + middle_name + first_name + "-" + mob + "-" + dob + "-" + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + middle_name + first_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + middle_name + first_name + "." + mob + "." + dob + "." + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + middle_name + first_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(last_name + middle_name + first_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(last_name + " " + middle_name + first_name + mob + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + middle_name + first_name + mob + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + middle_name + first_name + mob + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + middle_name + first_name + mob + yob)
wordlist.write("\n")
wordlist.write(last_name + " " + middle_name + first_name + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + middle_name + first_name + "_" + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + middle_name + first_name + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + middle_name + first_name + "-" + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + middle_name + first_name + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + middle_name + first_name + "." + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + middle_name + first_name + yob)
wordlist.write("\n")
wordlist.write(last_name + middle_name + first_name + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + middle_name + mob + "_" + dob + "_" + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + middle_name + mob + "-" + dob + "-" + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + middle_name + mob + "." + dob + "." + yob)
wordlist.write("\n")
wordlist.write(last_name + middle_name + mob + dob + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + middle_name + mob + "_" + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + middle_name + mob + "-" + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + middle_name + mob + "." + yob)
wordlist.write("\n")
wordlist.write(last_name + middle_name + mob + yob)
wordlist.write("\n")
wordlist.write(last_name + "_" + middle_name + yob)
wordlist.write("\n")
wordlist.write(last_name + "-" + middle_name + yob)
wordlist.write("\n")
wordlist.write(last_name + "." + middle_name + yob)
wordlist.write("\n")
wordlist.write(last_name + middle_name + yob)
wordlist.write("\n")
wordlist.write(mob + dob + yob)
wordlist.write("\n")
wordlist.write(mob + " " + dob + " " + yob)
wordlist.write("\n")
wordlist.write(mob + "." + dob + "." + yob)
wordlist.write("\n")
wordlist.write(mob + "_" + dob + "_" + yob)
wordlist.write("\n")
wordlist.write(mob + "-" + dob + "-" + yob)
wordlist.close()

print """
[+]...Wordlist Complete
\n[!]...Wordlist saved as, 'uni-wordlist.txt'
##############################################################
"""
cont = raw_input("\n[!]...Press 'Return' to Continue")


